### ISSUE TITLE
Create new bullet

### ISSUE THREAD

**Issue by robkruger** [djog/djog_unos_2019#105] opened 2019-11-23 10:55 UTC
Currently, the machine gun nests shoot shells, which isn't realistic of course. We need new bullets.

Create a enum class named `ProjectileType`, add `shell`, `bullet` and `tracer` in there and rename the `Shell` class to `Projectiles`. Modify that class so that it has a variable which holds it's type and it has a custom texture for all the bullet types.
Another option, although less efficient, is to create a new class named `Bullet` and copy almost all the code from the shell class but with another texture.

**Comment by Joshua260403** [comment] 2019-11-23 11:02
Projectile

**Comment by Rijk-van-Putten** [comment] 2019-11-23 11:03
👍  but is a tracer a projectile?

**Comment by Joshua260403** [comment] 2019-11-23 11:20
Yes, It's a type of bullet

**Comment by richelbilderbeek** [comment] 2019-11-23 11:24
@robkruger: you suggest to use inheritance here with 'Projectile' as the base class. I strongly advice against it, as inheritance is hard to use correctly and easy to use incorrectly :rainbow: . 

An easy alternative is to use a 'Projectile' class, with an enum type called 'type'. This is the approach we used in Nature Zen. It is simple and scales better (i.e. it prevents a class explosion).

OTOH, the problem is simple enough to try it out in this context, as it will be relatively easy to undo at the moment Team Octane regrets the decision to use it. 

I leave it up to you (or the whole Team) to pick either:

 * (1) experiment with inheritance using a 'Projectile' base class. You volunteer for clean-up duty if needed :grin:  
 * (2) use a class 'Projectile' that has an enum type, e.g. 'Shell'. The rock-solid alternative!

**Comment by robkruger** [comment] 2019-11-23 11:32
@richelbilderbeek I meant the Nature Zen approach, but maybe didn't explain it too well...

**Comment by richelbilderbeek** [comment] 2019-11-23 11:34
Cool, than you have my complete blessing! Good luck implementing it :+1:

**Comment by Rijk-van-Putten** [comment] 2019-11-23 16:19
I'll create a projectile system with enums. It'll be a bit more complex so I'll remove the good first issue label.

**Comment by Rijk-van-Putten** [comment] 2019-11-23 18:18
I created a projectile system & merged.

**Closed by Rijk-van-Putten** 2019-11-23 18:18 UTC
Labels: medium priority
